-- Schema for SeaTrack Transactions

CREATE TABLE public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Create policy to allow inserts (useful for anon key access from the app)
CREATE POLICY "Enable insert for authenticated and anon users"
ON public.transactions
FOR INSERT
WITH CHECK (true);

-- Create policy to allow reading for anon users (if you want to show it in the app later)
CREATE POLICY "Enable read access for all users"
ON public.transactions
FOR SELECT
USING (true);
